version: "3.9"
services:
  api:
    build: .
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskflow?schema=public
      - REDIS_URL=redis://redis:6379
      - JWT_ACCESS_SECRET=change_me_access
      - JWT_REFRESH_SECRET=change_me_refresh
      - JWT_ACCESS_EXPIRES=15m
      - JWT_REFRESH_EXPIRES=7d
      - SWAGGER_TITLE=Taskflow API
      - SWAGGER_VERSION=1.0.0
      - SWAGGER_DESCRIPTION=SaaS Task Manager API
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
volumes:
  pgdata:
